FROM python:3.11-slim

ARG PROJECT_DIR=project
ENV PROJECT_DIR=${PROJECT_DIR}
ENV PYTHONDONTWRITEBYTECODE=1 PYTHONUNBUFFERED=1 PIP_NO_CACHE_DIR=1 DJANGO_DEBUG=1

RUN apt-get update && apt-get install -y --no-install-recommends \
    bash ca-certificates build-essential util-linux wget git curl unzip zip \
 && rm -rf /var/lib/apt/lists/*

WORKDIR /app

RUN wget https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-Linux-x86_64.sh -O /tmp/Miniforge3-Linux-x86_64.sh
RUN /bin/bash /tmp/Miniforge3-Linux-x86_64.sh -b -p /opt/conda && \
    rm /tmp/Miniforge3-Linux-x86_64.sh && \
    echo "export PATH=/opt/conda/bin:$PATH" > /etc/profile.d/conda.sh

ENV PATH /opt/conda/bin:$PATH
ENV SDKMAN_DIR /root/.sdkman
ENV HOME=/root

RUN conda config --env --add channels bioconda && \
    conda config --env --add channels conda-forge && \
    conda config --system --add channels bioconda && \
    conda config --system --add channels conda-forge && \
    conda create -y -n broker python=3 bwa samtools && \
    /opt/conda/bin/activate broker && \
    pip install Django requests biopython phonenumbers django-widget-tweaks django-phonenumber-field django-clearcache django-q2 xmltodict blessed pillow nextflow jsonschema

RUN curl -s https://get.sdkman.io | /usr/bin/bash 
RUN chmod +x /root/.sdkman/bin/sdkman-init.sh

RUN bash -lc 'source "/root/.sdkman/bin/sdkman-init.sh"; yes | sdk install java 17.0.10-tem'

RUN bash -lc 'source "/root/.sdkman/bin/sdkman-init.sh"; curl -s https://get.nextflow.io | /usr/bin/bash && \
    chmod +x /app/nextflow && \
    ln -s /app/nextflow /usr/local/bin/nextflow'

RUN mkdir /tmp/git && \
    git clone https://github.com/metagenomics/submg.git /tmp/git && \
    conda create -y -n submg python=3.9 openjdk=23.0.1 

RUN bash -lc 'source /opt/conda/bin/activate submg && \
    pip install /tmp/git && \
    mkdir -p /opt/conda/envs/submg/lib/python3.9/site-packages/submg'

COPY webin-cli-8.1.0.jar /opt/conda/envs/submg/lib/python3.9/site-packages/submg/webin-cli-7.0.1.jar
COPY webin-cli-8.1.0.jar /app/project/webin-cli-8.1.0.jar
COPY checkm_mem_increase.nf /app/project/checkm_mem_increase.nf

# COPY requirements.txt /app/requirements.txt
# RUN python -m pip install --upgrade pip && python -m pip install -r /app/requirements.txt

COPY project /app/project

# RUN find /app \( -name __pycache__ -o -name \*.sqlite3 -o -name debug.log \) -exec rm -rf {} \;
# RUN rm -rf /app/project/media/test/*

# Keep entrypoint out of /app to avoid being shadowed by the bind mount
# COPY docker-entrypoint.sh /usr/local/bin/docker-entrypoint.sh
# RUN chmod +x /usr/local/bin/docker-entrypoint.sh

# EXPOSE 8000
# ENTRYPOINT ["bash","/usr/local/bin/docker-entrypoint.sh"]
# web's default command (worker overrides this in compose)
CMD ["bash","-lc","python \"$PROJECT_DIR/manage.py\" runserver qcluster"]

