services:
  web:
    build:
      context: .
      # dockerfile: Dockerfile-web
    image: web:latest
    environment:
      ROLE: web
      RUN_MIGRATIONS: "1"
      RUN_COLLECTSTATIC: "1"
      DJANGO_DEBUG: "1"
    env_file:
      - .env    # uncomment only if you have a real .env
    volumes:
      - ./project/db.sqlite3:/app/project/db.sqlite3
      - ./project/media/broker:/app/project/media/broker
    ports:
      - "8000:8000"
    entrypoint: ["bash","/usr/local/bin/docker-entrypoint.sh"]
    command: bash -lc 'python "project/manage.py" runserver 0.0.0.0:8000'
    restart: unless-stopped
    network_mode: bridge

  qworker:
    build:
      context: .
      # dockerfile: Dockerfile-qworker
    image: qworker:latest
    environment:
      ROLE: worker
      DJANGO_DEBUG: "1"
    env_file:
      - .env
    volumes:
      - ./project/db.sqlite3:/app/project/db.sqlite3
      - ./project/media/broker:/app/project/media/broker
    depends_on:
      - web
    command: bash -lc 'python "project/manage.py" qcluster'
    restart: unless-stopped
    network_mode: bridge
