MIXS_METADATA_STANDARDS = [
    ('Agriculture', 'Agriculture'),
    ('Air', 'Air'),
    ('BuiltEnvironment', 'Built Environment'),
    ('FoodAnimalAndAnimalFeed', 'Food Animal and Animal Feed'),
    ('FoodFarmEnvironment', 'Food Farm Environment'),
    ('FoodFoodProductionFacility', 'Food Production Facility'),
    ('FoodHumanFoods', 'Human Foods'),
    ('HostAssociated', 'Host Associated'),
    ('HumanAssociated', 'Human Associated'),
    ('HumanGut', 'Human Gut'),
    ('HumanOral', 'Human Oral'),
    ('HumanSkin', 'Human Skin'),
    ('HumanVaginal', 'Human Vaginal'),
    ('HydrocarbonResourcesCores', 'Hydrocarbon Resources Cores'),
    ('HydrocarbonResourcesFluidsSwabs', 'Hydrocarbon Resources Fluids Swabs'),
    ('MicrobialMatBiofilm', 'Microbial Mat Biofilm'),
    ('MiscellaneousNaturalOrArtificialEnvironment', 'Miscellaneous Natural or Artificial Environment'),
    ('PlantAssociated', 'Plant Associated'),
    ('Sediment', 'Sediment'),
    ('Soil', 'Soil'),
    ('SymbiontAssociated', 'Symbiont Associated'),
    ('WastewaterSludge', 'Wastewater Sludge'),
    ('Water', 'Water'),
]