# Generated by Django 5.2.4 on 2025-07-07 10:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Sequencing Order Management', help_text='The name of your application', max_length=200)),
                ('organization_name', models.CharField(default='Helmholtz Centre for Infection Research', help_text='Full name of your organization', max_length=200)),
                ('organization_short_name', models.CharField(default='HZI', help_text='Short name or acronym', max_length=50)),
                ('tagline', models.CharField(blank=True, default='Streamlining sequencing requests and ensuring compliance with MIxS standards', help_text='A brief description or tagline for your site', max_length=500)),
                ('contact_email', models.EmailField(default='sequencing@helmholtz-hzi.de', help_text='Primary contact email address', max_length=254)),
                ('website_url', models.URLField(blank=True, default='https://www.helmholtz-hzi.de', help_text="Organization's main website URL")),
                ('logo', models.ImageField(blank=True, help_text='Organization logo (recommended size: 200x50px)', null=True, upload_to='branding/')),
                ('favicon', models.ImageField(blank=True, help_text='Favicon for browser tab (recommended: 32x32px .ico or .png)', null=True, upload_to='branding/')),
                ('primary_color', models.CharField(default='#3273dc', help_text='Primary theme color in hex format (e.g., #3273dc)', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color code (e.g., #3273dc)', regex='^#[0-9a-fA-F]{6}$')])),
                ('secondary_color', models.CharField(default='#2366d1', help_text='Secondary theme color in hex format', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color code (e.g., #2366d1)', regex='^#[0-9a-fA-F]{6}$')])),
                ('footer_text', models.TextField(blank=True, default='', help_text='Additional footer text (HTML allowed)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
