# Generated by Django 5.2.4 on 2025-07-10 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='ena_center_name',
            field=models.CharField(blank=True, default='', help_text='Center name for ENA submissions (optional)', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='ena_password',
            field=models.CharField(blank=True, default='', help_text='ENA account password (encrypted in database)', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='ena_test_mode',
            field=models.BooleanField(default=True, help_text='Use ENA test server for submissions (recommended for testing)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='ena_username',
            field=models.CharField(blank=True, default='', help_text='ENA Webin account username (e.g., Webin-XXXXXX)', max_length=100),
        ),
    ]
