# Generated by Django 5.2.4 on 2025-07-14 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_sampleset_field_overrides_sampleset_selected_fields_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='checklist_changed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sampleset',
            name='field_overrides',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='sampleset',
            name='selected_fields',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
