# Generated by Django 5.2.4 on 2025-07-07 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_sitesettings_empty_projects_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('ready_for_sequencing', 'Ready for Sequencing'), ('sequencing_in_progress', 'Sequencing in Progress'), ('sequencing_completed', 'Sequencing Completed'), ('data_processing', 'Data Processing'), ('data_delivered', 'Data Delivered'), ('completed', 'Completed')], default='draft', help_text='Current status of the sequencing order', max_length=30),
        ),
        migrations.AddField(
            model_name='order',
            name='status_notes',
            field=models.TextField(blank=True, help_text='Additional notes about the current status'),
        ),
        migrations.AddField(
            model_name='order',
            name='status_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
