# Generated by Django 5.2.4 on 2025-07-21 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_add_sequencing_data_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='submgrun',
            name='tax_ids',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
