# Generated by Django 5.2.4 on 2025-07-07 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_order_status_order_status_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='order_form_description',
            field=models.TextField(blank=True, default='Provide detailed information for your sequencing order including contact details, sample information, and sequencing preferences.', help_text='Description shown on order creation form'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='order_form_title',
            field=models.CharField(default='Create Sequencing Order', help_text='Title shown on order creation form', max_length=200),
        ),
    ]
