# Generated by Django 5.2.4 on 2025-07-07 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_sitesettings_order_form_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='library',
            field=models.CharField(blank=True, choices=[('choice1', 'Choice 1'), ('choice2', 'Choice 2'), ('other', 'Other')], max_length=100, null=True),
        ),
    ]
