# Generated by Django 5.0.4 on 2024-04-08 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_sample_mixs_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='mixs_metadata_standard',
            field=models.CharField(blank=True, choices=[('Air', 'Air'), ('HostAssociated', 'Host Associated'), ('HumanAssociated', 'Human Associated'), ('HumanGut', 'Human Gut'), ('HumanOral', 'Human Oral'), ('HumanSkin', 'Human Skin'), ('HumanVaginal', 'Human Vaginal'), ('MicrobialMatBiofilm', 'Microbial Mat Biofilm'), ('MiscellaneousNaturalOrArtificialEnvironment', 'Miscellaneous Natural or Artificial Environment'), ('PlantAssociated', 'Plant Associated'), ('Sediment', 'Sediment'), ('Soil', 'Soil'), ('WastewaterSludge', 'Wastewater Sludge'), ('Water', 'Water')], max_length=100, null=True),
        ),
    ]
