# Generated by Django 5.0.4 on 2024-04-09 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_sample_mixs_metadata_standard'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='filename_forward',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Filename (Forward, R1)'),
        ),
        migrations.AddField(
            model_name='sample',
            name='filename_reverse',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Filename (Reverse, R2)'),
        ),
        migrations.AddField(
            model_name='sample',
            name='status',
            field=models.CharField(blank=True, choices=[('in_preparation', 'In Preparation'), ('sequencing', 'Sequencing'), ('finished', 'Finished'), ('uploaded_to_ENA', 'Uploaded to ENA')], max_length=20, null=True, verbose_name='Status'),
        ),
    ]
