# Generated by Django 5.2.4 on 2025-07-07 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_order_library'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='metadata_checklist_description',
            field=models.TextField(blank=True, default="Select the appropriate MIxS (Minimum Information about any Sequence) standard for your samples. This determines what metadata fields you'll need to fill out.", help_text='Description shown on metadata checklist selection page'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='metadata_checklist_title',
            field=models.CharField(default='Configure Metadata Checklists', help_text='Title shown on metadata checklist selection page', max_length=200),
        ),
    ]
