# Generated by Django 5.0.4 on 2024-04-09 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_sample_filename_forward_sample_filename_reverse_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sample',
            old_name='internal_id',
            new_name='date',
        ),
        migrations.AlterField(
            model_name='sample',
            name='status',
            field=models.CharField(blank=True, choices=[('in_preparation', 'In Preparation'), ('sequencing', 'Sequencing'), ('finished', 'Finished'), ('uploaded_to_ENA', 'Uploaded to ENA')], max_length=20, null=True),
        ),
    ]
