# Generated by Django 5.2.4 on 2025-07-07 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_sitesettings_metadata_checklist_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='submission_instructions',
            field=models.TextField(blank=True, default='<h4>Next Steps After Submission:</h4>\n<ol>\n<li><strong>Sample Preparation:</strong> Ensure your samples are properly labeled with the sample IDs you provided.</li>\n<li><strong>Sample Shipping:</strong> Ship your samples to:\n    <address>\n    Sequencing Facility<br>\n    Helmholtz Centre for Infection Research<br>\n    Inhoffenstraße 7<br>\n    38124 Braunschweig, Germany\n    </address>\n</li>\n<li><strong>Include Documentation:</strong> Print and include your order confirmation with the samples.</li>\n<li><strong>Tracking:</strong> You will receive email updates on the status of your sequencing order.</li>\n</ol>\n<p>For questions, contact: <a href="mailto:sequencing@helmholtz-hzi.de">sequencing@helmholtz-hzi.de</a></p>', help_text='Instructions shown after order submission (HTML allowed)'),
        ),
    ]
