# Generated by Django 5.0.4 on 2024-04-10 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_internal_id_sample_date_alter_sample_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='nf_core_mag_outdir',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
