# Generated by Codex on behalf of user request

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_alter_ena_binned_metagenome_assembly_quality_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submgrun",
            name="yaml",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="submgrun",
            name="tax_ids",
            field=models.TextField(blank=True, null=True),
        ),
    ]
