# Generated by Django 5.2.4 on 2025-07-07 23:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_formtemplate_formsubmission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('note_type', models.CharField(choices=[('internal', 'Internal Note'), ('user_visible', 'User Visible Note'), ('status_change', 'Status Change'), ('rejection', 'Rejection Note')], default='internal', max_length=20)),
                ('content', models.TextField(help_text='Note content or status change description')),
                ('old_status', models.CharField(blank=True, help_text='Previous status (for status changes)', max_length=30)),
                ('new_status', models.CharField(blank=True, help_text='New status (for status changes)', max_length=30)),
                ('is_rejection', models.BooleanField(default=False, help_text='Whether this note represents a rejection')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='app.order')),
                ('user', models.ForeignKey(help_text='User who created this note', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
