# Generated by Django 5.2.4 on 2025-07-10 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_statusnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='sampleset',
            name='field_overrides',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='sampleset',
            name='selected_fields',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
