# Generated by Django 5.2.5 on 2025-10-22 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_magrun_project_and_project_submission_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectsubmission',
            name='projects',
            field=models.ManyToManyField(blank=True, to='app.project'),
        ),
    ]
