# Generated by Django 5.0.4 on 2024-04-10 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_submission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pipelines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(blank=True, choices=[('in_preparation', 'In Preparation'), ('sequencing', 'Sequencing'), ('finished', 'Finished'), ('uploaded_to_ENA', 'Uploaded to ENA')], max_length=20, null=True)),
                ('output_folder', models.CharField(blank=True, max_length=255, null=True)),
                ('samples', models.ManyToManyField(to='app.sample')),
            ],
        ),
    ]
