# Generated by Django 5.2.5 on 2025-10-24 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_update_assembly_bin_relationships'),
    ]

    operations = [
        migrations.AddField(
            model_name='submgrun',
            name='quality_files',
            field=models.TextField(blank=True, null=True),
        ),
    ]
