# Generated by Django 6.0.5 on 2026-06-02 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_add_quality_files_to_submg_run'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='contact_email',
            field=models.EmailField(default='contact@example.com', help_text='Primary contact email address', max_length=254),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='organization_name',
            field=models.CharField(default='Your Organization Name', help_text='Full name of your organization', max_length=200),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='organization_short_name',
            field=models.CharField(default='ORG', help_text='Short name or acronym', max_length=50),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='submission_instructions',
            field=models.TextField(blank=True, default='<h4>Next Steps After Submission:</h4>\n<ol>\n<li><strong>Sample Preparation:</strong> Ensure your samples are properly labeled with the sample IDs you provided.</li>\n<li><strong>Sample Shipping:</strong> Ship your samples to:\n    <address>\n    Your Sequencing Facility<br>\n    Your Organization Name<br>\n    Street Address<br>\n    City, Country\n    </address>\n</li>\n<li><strong>Include Documentation:</strong> Print and include your order confirmation with the samples.</li>\n<li><strong>Tracking:</strong> You will receive email updates on the status of your sequencing order.</li>\n</ol>\n<p>For questions, contact: <a href="mailto:contact@example.com">contact@example.com</a></p>', help_text='Instructions shown after order submission (HTML allowed)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='tagline',
            field=models.CharField(blank=True, default='Demo instance for exploring the application', help_text='A brief description or tagline for your site', max_length=500),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='website_url',
            field=models.URLField(blank=True, default='https://www.example.com', help_text="Organization's main website URL"),
        ),
    ]
